// frontend-training/app_goal/app/javascript/components/shared/FeedItem.tsx
import axios from "axiosClient";
import * as React from "react";
import GravatarImage from "./GravatarImage";

interface User {
  id: number;
  name: string;
  gravatar_url: string;
  is_current_user: boolean;
}

interface Feed {
  id: number;
  content: string;
  image_url?: string;
  created_at_time_ago_in_words: string;
  user: User;
}

interface Props {
  feed: Feed;
  onDelete: (id: number) => void;
}

const FeedItem = (props: Props) => {
  const handleClickDeleteButton = async (event: React.MouseEvent) => {
    event.preventDefault();

    if (confirm("You sure?")) {
      await axios.delete(`/microposts/${props.feed.id}.json`);

      props.onDelete(props.feed.id);
    }
  };

  return (
    <>
      <GravatarImage user={props.feed.user} />
      <span className="user">
        <a href={`/users/${props.feed.user.id}`}>{props.feed.user.name}</a>
      </span>
      <span className="content">
        {props.feed.content}
        {props.feed.image_url && <img src={props.feed.image_url} />}
      </span>
      <span className="timestamp">
        Posted {props.feed.created_at_time_ago_in_words} ago.{" "}
        {props.feed.user.is_current_user && (
          <a onClick={handleClickDeleteButton}>delete</a>
        )}
      </span>
    </>
  );
};

export default FeedItem;

// mobile-training/app_start/app/javascripts/packs/FeedItem.vue
<template>
  <li :id="'micropost-' + feed.id">
    <user-image :user="user"></user-image>
    <user-name :user="user"></user-name>
    <span class="content">
      {{ feed.content }}
      <img :src="feed.picture_url" v-if="feed.picture_url" />
    </span>
    <span class="timestamp">
      Posted {{ feed.created_at_time_ago_in_words }} ago
      <a @click="deleteMicropost" v-if="user.is_current_user">
        delete
      </a>
    </span>
  </li>
</template>

<script>
import axios from './axiosClient'
import UserImage from './UserImage.vue'
import UserName from './UserName.vue'

export default {
  components: {
    UserImage,
    UserName
  },
  props: {
    feed: Object,
    user: Object,
    onDelete: Function
  },
  methods: {
    async deleteMicropost() {
      if (confirm('You sure?')) {
        await axios.delete(`/microposts/${this.feed.id}.json`)
        this.onDelete(this.feed.id)
      }
    }
  }
}
</script>
